# [Server]
# ip or smth ig?

questions = [
    ["On what floor is the sleeping area?", ["1", "2", "3", "4"], 2,],
    ["Can we use the elevators?", ["Yes", "Never", "With Baggage", "If you're nice"], 3,],
    ["What time did the doors lock after lunch?", ["3pm", "4pm", "5pm", "6pm"], 2,],
]


